version: "3.7"

services:
  tagfinder:
    build: ./
    container_name: tagfinder
    restart: always
    volumes:
      - ./:/src
    environment:
      - APP_NAME=tagfinder
    ports:
      - "8080:5000"
